import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Topbar from "@/components/Topbar";
import CallBubble from "@/components/CallBubble";
import WPButton from "@/components/WPButton";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Edid Çelik Kapı Sistmeleri - Kapı Onarım & Çelik Kapı Modelleri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <head>
        
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <CallBubble />
        <WPButton />
        <Topbar />
        <Navbar />
        {children}
<script
          async
          src="https://www.googletagmanager.com/gtag/js?id=AW-17653970524"
        ></script>
        <script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'AW-17653970524');
        </script>
        <Footer />
      </body>
    </html>
  );
}
